import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from '~/features/theme/theme.provider'
import { Header } from '@repo/ui/components/header'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" suppressHydrationWarning>
      <body>
        <Header />
        <ThemeProvider>
          <main className="container">
            {children}
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
