@baseUrl = http://localhost:3333
@tenant = alemanha

### AUTH

# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{ "tenant": "{{tenant}}", "username": "gu.rmiguel@gmail.com" }

###
@refreshToken = {{login.response.body.$.refresh_token}}
@accessToken = {{login.response.body.$.access_token}}
###


# @name refresh
POST {{baseUrl}}/auth/refresh
Content-Type: application/json

{ "refresh_token": "{{refreshToken}}" }

###


# @name getProfile
GET {{baseUrl}}/users
Authorization: Bearer {{accessToken}}

### Territories

# @name listTerritories
GET {{baseUrl}}/territories
Authorization: Bearer {{accessToken}}

###
# @prompt territoryId
# @name getTerritory
GET {{baseUrl}}/territories/{{territoryId}}
Authorization: Bearer {{accessToken}}

###

# @name createTerritories
POST {{baseUrl}}/territories
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "number": "1",
  "color": "#000000",
  "hidden": false,
  "map": null
}

###
# @prompt territoryId
# @name updateTerritory
PATCH {{baseUrl}}/territories/{{territoryId}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "hidden": false
}

###
# @prompt territoryId
# @name deleteTerritory
DELETE {{baseUrl}}/territories/{{territoryId}}
Authorization: Bearer {{accessToken}}

###
# @prompt territoryId
# @name addStreet
POST {{baseUrl}}/territories/{{territoryId}}/streets
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "name": "Rua Teste"
}

###
# @prompt territoryId
# @prompt streetId
# @name updateStreet
PATCH {{baseUrl}}/territories/{{territoryId}}/streets/{{streetId}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "name": "Rua Teste 2"
}

###
# @prompt territoryId
# @prompt streetId
# @name deleteStreet
DELETE {{baseUrl}}/territories/{{territoryId}}/streets/{{streetId}}
Authorization: Bearer {{accessToken}}

###
# @prompt territoryId
# @prompt streetId
# @name addHouse
POST {{baseUrl}}/territories/{{territoryId}}/streets/{{streetId}}/houses
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "type": "Casa",
  "number": "1",
  "complement": "Fundos",
  "observation": "",
  "phones": [
    "11 99999-9999"
  ]
}

###
# @prompt territoryId
# @prompt streetId
# @prompt houseId
# @name updateHouse
PATCH {{baseUrl}}/territories/{{territoryId}}/streets/{{streetId}}/houses/{{houseId}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "number": "2"
}

###
# @prompt territoryId
# @prompt streetId
# @prompt houseId
# @name deleteHouse
DELETE {{baseUrl}}/territories/{{territoryId}}/streets/{{streetId}}/houses/{{houseId}}
Authorization: Bearer {{accessToken}}

###
# @prompt territoryId
# @prompt streetId
# @prompt houseId
# @name updateHouseStatus
POST {{baseUrl}}/territories/{{territoryId}}/streets/{{streetId}}/houses/{{houseId}}/status
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "status": "OK",
  "date": "2025-05-01T10:00:00.000Z"
}