@baseUrl = http://localhost:3333
@tenant = alemanha

### AUTH

# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{ "tenant": "{{tenant}}", "username": "gu.rmiguel@gmail.com" }

###
@refreshToken = {{login.response.body.$.refresh_token}}
@accessToken = {{login.response.body.$.access_token}}
###


# @name refresh
POST {{baseUrl}}/auth/refresh
Content-Type: application/json

{ "refresh_token": "{{refreshToken}}" }

###


# @name getProfile
GET {{baseUrl}}/users
Authorization: Bearer {{accessToken}}

### Territories

# @name listTerritories
GET {{baseUrl}}/territories
Authorization: Bearer {{accessToken}}

###

# @name createTerritories
POST {{baseUrl}}/territories
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "number": "1",
  "color": "#000000",
  "hidden": false,
  "map": null
}

###

# @name updateTerritory
PATCH {{baseUrl}}/territories/{{createTerritories.response.body.$.id}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "hidden": false
}

###

# @name deleteTerritory
DELETE {{baseUrl}}/territories/{{createTerritories.response.body.$.id}}
Authorization: Bearer {{accessToken}}

###

# @name addStreet
POST {{baseUrl}}/territories/{{createTerritories.response.body.$.id}}/streets
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "name": "Rua Teste"
}

###

# @name updateStreet
PATCH {{baseUrl}}/territories/{{createTerritories.response.body.$.id}}/streets/{{addStreet.response.body.$.id}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "name": "Rua Teste 2"
}

###

# @name deleteStreet
DELETE {{baseUrl}}/territories/{{createTerritories.response.body.$.id}}/streets/{{addStreet.response.body.$.id}}
Authorization: Bearer {{accessToken}}

###