@baseUrl = http://localhost:3333
@tenant = alemanha

### AUTH

# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json
x-tenant-id: {{tenant}}

{ "username": "gu.rmiguel@gmail.com" }

###
@refreshToken = {{login.response.body.$.refresh_token}}
@accessToken = {{login.response.body.$.access_token}}
###


# @name refresh
POST {{baseUrl}}/auth/refresh
Content-Type: application/json
x-tenant-id: {{tenant}}

{ "refresh_token": "{{refreshToken}}" }

###


# @name getProfile
GET {{baseUrl}}/users
Authorization: Bearer {{accessToken}}
x-tenant-id: {{tenant}}

###

# @name listTerritories
GET {{baseUrl}}/territories
Authorization: Bearer {{accessToken}}
x-tenant-id: {{tenant}}

###

# @name createTerritories
POST {{baseUrl}}/territories
Content-Type: application/json
Authorization: Bearer {{accessToken}}
x-tenant-id: {{tenant}}

{
  "number": "1",
  "color": "#000000",
  "hidden": false,
  "map": null
}